### ISSUE TITLE
Update copyright notice years?

### ISSUE THREAD

**Issue by basil-conto** [kyleam/bog#11]
[`(maintain) Copyright Notices`](https://www.gnu.org/prep/maintain/html_node/Copyright-Notices.html) says notices need include only those years which saw non-trivial changes, and the only changes to `bog.el` and `bog-tests.el` since 2016 have been my trivial fixups.

So, I'm simply curious: are we OK for now, or should the notices of these files be updated beyond 2016?

**Comment by kyleam** [comment]
Good question.

There have been cases where I've failed badly at remembering to update copyright lines, particularly if the first time I touch a package in a given year is well after the start of the year.  But here I think it's OK that my last copyright line is dated 2016.  As you mentioned, I haven't made a change after 2016 that wasn't merging or releasing your changes.

My understanding is that every contributor of nontrivial changes should have a copyright line (assuming the package isn't FSF-copyrighted).  This can lead to some pretty ugly file headers ([example]), but most packages aren't so fortunate :> (There is also the "Foo contributors" approach; I don't know whether that is considered good practice.)

So, back at you :]  Should _you_ add a copyright line?  I'd say "please do", but that's of course up to you.

[example]: https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/python-xyz.scm#n2

**Comment by basil-conto** [comment]
> This can lead to some pretty ugly file headers ([example](https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/python-xyz.scm#n2))

Beauty is in the eye of the beheader. ;)

> Should _you_ add a copyright line? I'd say "please do", but that's of course up to you.

I'm not sure; my commits from 2017 definitely sum up to a negligible line count, and those from 2018 just about reach the threshold of ~15 lines. If you think that's legally significant enough, I'd be happy to oblige; otherwise, I'm happy with not being attributed and not claiming ownership in any way. :)

**Comment by kyleam** [comment]
> otherwise, I'm happy with not being attributed and not claiming ownership in any way. :)

Works for me :]
